###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:
    mariadb:
        image: 'mariadb:10.6'
        working_dir: /application
        volumes:
            - '.:/application'
        environment:
            - MYSQL_ROOT_PASSWORD=film
            - MYSQL_DATABASE=film
            - MYSQL_USER=film
            - MYSQL_PASSWORD=film
        ports:
            - '24003:3306'

    webserver:
        image: 'nginx:alpine'
        working_dir: /application
        volumes:
            - '.:/application'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '24000:80'

    php-fpm:
        build: phpdocker/php-fpm
        working_dir: /application
        environment:
            XDEBUG_CONFIG: "mode=debug client_host=host.docker.internal start_with_request=yes"
            PHP_IDE_CONFIG: "serverName=film"
        extra_hosts:
            - "host.docker.internal:host-gateway"
        volumes:
            - '.:/application'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'
