CREATE TABLE countries (id VARCHAR(64) NOT NULL, value VARCHAR(64) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

INSERT INTO countries (`id`, `value`) VALUES ('AU', 'Австралия');
INSERT INTO countries (`id`, `value`) VALUES ('AT', 'Австрия');
INSERT INTO countries (`id`, `value`) VALUES ('AZ', 'Азербайджан');
INSERT INTO countries (`id`, `value`) VALUES ('AX', 'Аландские о-ва');
INSERT INTO countries (`id`, `value`) VALUES ('AL', 'Албания');
INSERT INTO countries (`id`, `value`) VALUES ('DZ', 'Алжир');
INSERT INTO countries (`id`, `value`) VALUES ('AS', 'Американское Самоа');
INSERT INTO countries (`id`, `value`) VALUES ('AI', 'Ангилья');
INSERT INTO countries (`id`, `value`) VALUES ('AO', 'Ангола');
INSERT INTO countries (`id`, `value`) VALUES ('AD', 'Андорра');
INSERT INTO countries (`id`, `value`) VALUES ('AQ', 'Антарктида');
INSERT INTO countries (`id`, `value`) VALUES ('AG', 'Антигуа и Барбуда');
INSERT INTO countries (`id`, `value`) VALUES ('AR', 'Аргентина');
INSERT INTO countries (`id`, `value`) VALUES ('AM', 'Армения');
INSERT INTO countries (`id`, `value`) VALUES ('AW', 'Аруба');
INSERT INTO countries (`id`, `value`) VALUES ('AF', 'Афганистан');
INSERT INTO countries (`id`, `value`) VALUES ('BS', 'Багамы');
INSERT INTO countries (`id`, `value`) VALUES ('BD', 'Бангладеш');
INSERT INTO countries (`id`, `value`) VALUES ('BB', 'Барбадос');
INSERT INTO countries (`id`, `value`) VALUES ('BH', 'Бахрейн');
INSERT INTO countries (`id`, `value`) VALUES ('BY', 'Беларусь');
INSERT INTO countries (`id`, `value`) VALUES ('BZ', 'Белиз');
INSERT INTO countries (`id`, `value`) VALUES ('BE', 'Бельгия');
INSERT INTO countries (`id`, `value`) VALUES ('BJ', 'Бенин');
INSERT INTO countries (`id`, `value`) VALUES ('BM', 'Бермудские о-ва');
INSERT INTO countries (`id`, `value`) VALUES ('BG', 'Болгария');
INSERT INTO countries (`id`, `value`) VALUES ('BO', 'Боливия');
INSERT INTO countries (`id`, `value`) VALUES ('BQ', 'Бонэйр, Синт-Эстатиус и Саба');
INSERT INTO countries (`id`, `value`) VALUES ('BA', 'Босния и Герцеговина');
INSERT INTO countries (`id`, `value`) VALUES ('BW', 'Ботсвана');
INSERT INTO countries (`id`, `value`) VALUES ('BR', 'Бразилия');
INSERT INTO countries (`id`, `value`) VALUES ('IO', 'Британская территория в Индийском океане');
INSERT INTO countries (`id`, `value`) VALUES ('BN', 'Бруней-Даруссалам');
INSERT INTO countries (`id`, `value`) VALUES ('BF', 'Буркина-Фасо');
INSERT INTO countries (`id`, `value`) VALUES ('BI', 'Бурунди');
INSERT INTO countries (`id`, `value`) VALUES ('BT', 'Бутан');
INSERT INTO countries (`id`, `value`) VALUES ('VU', 'Вануату');
INSERT INTO countries (`id`, `value`) VALUES ('VA', 'Ватикан');
INSERT INTO countries (`id`, `value`) VALUES ('GB', 'Великобритания');
INSERT INTO countries (`id`, `value`) VALUES ('HU', 'Венгрия');
INSERT INTO countries (`id`, `value`) VALUES ('VE', 'Венесуэла');
INSERT INTO countries (`id`, `value`) VALUES ('VG', 'Виргинские о-ва (Великобритания)');
INSERT INTO countries (`id`, `value`) VALUES ('VI', 'Виргинские о-ва (США)');
INSERT INTO countries (`id`, `value`) VALUES ('UM', 'Внешние малые о-ва (США)');
INSERT INTO countries (`id`, `value`) VALUES ('TL', 'Восточный Тимор');
INSERT INTO countries (`id`, `value`) VALUES ('VN', 'Вьетнам');
INSERT INTO countries (`id`, `value`) VALUES ('GA', 'Габон');
INSERT INTO countries (`id`, `value`) VALUES ('HT', 'Гаити');
INSERT INTO countries (`id`, `value`) VALUES ('GY', 'Гайана');
INSERT INTO countries (`id`, `value`) VALUES ('GM', 'Гамбия');
INSERT INTO countries (`id`, `value`) VALUES ('GH', 'Гана');
INSERT INTO countries (`id`, `value`) VALUES ('GP', 'Гваделупа');
INSERT INTO countries (`id`, `value`) VALUES ('GT', 'Гватемала');
INSERT INTO countries (`id`, `value`) VALUES ('GN', 'Гвинея');
INSERT INTO countries (`id`, `value`) VALUES ('GW', 'Гвинея-Бисау');
INSERT INTO countries (`id`, `value`) VALUES ('DE', 'Германия');
INSERT INTO countries (`id`, `value`) VALUES ('GG', 'Гернси');
INSERT INTO countries (`id`, `value`) VALUES ('GI', 'Гибралтар');
INSERT INTO countries (`id`, `value`) VALUES ('HN', 'Гондурас');
INSERT INTO countries (`id`, `value`) VALUES ('HK', 'Гонконг (САР)');
INSERT INTO countries (`id`, `value`) VALUES ('GD', 'Гренада');
INSERT INTO countries (`id`, `value`) VALUES ('GL', 'Гренландия');
INSERT INTO countries (`id`, `value`) VALUES ('GR', 'Греция');
INSERT INTO countries (`id`, `value`) VALUES ('GE', 'Грузия');
INSERT INTO countries (`id`, `value`) VALUES ('GU', 'Гуам');
INSERT INTO countries (`id`, `value`) VALUES ('DK', 'Дания');
INSERT INTO countries (`id`, `value`) VALUES ('JE', 'Джерси');
INSERT INTO countries (`id`, `value`) VALUES ('DJ', 'Джибути');
INSERT INTO countries (`id`, `value`) VALUES ('DM', 'Доминика');
INSERT INTO countries (`id`, `value`) VALUES ('DO', 'Доминиканская Республика');
INSERT INTO countries (`id`, `value`) VALUES ('EG', 'Египет');
INSERT INTO countries (`id`, `value`) VALUES ('ZM', 'Замбия');
INSERT INTO countries (`id`, `value`) VALUES ('EH', 'Западная Сахара');
INSERT INTO countries (`id`, `value`) VALUES ('ZW', 'Зимбабве');
INSERT INTO countries (`id`, `value`) VALUES ('IL', 'Израиль');
INSERT INTO countries (`id`, `value`) VALUES ('IN', 'Индия');
INSERT INTO countries (`id`, `value`) VALUES ('ID', 'Индонезия');
INSERT INTO countries (`id`, `value`) VALUES ('JO', 'Иордания');
INSERT INTO countries (`id`, `value`) VALUES ('IQ', 'Ирак');
INSERT INTO countries (`id`, `value`) VALUES ('IR', 'Иран');
INSERT INTO countries (`id`, `value`) VALUES ('IE', 'Ирландия');
INSERT INTO countries (`id`, `value`) VALUES ('IS', 'Исландия');
INSERT INTO countries (`id`, `value`) VALUES ('ES', 'Испания');
INSERT INTO countries (`id`, `value`) VALUES ('IT', 'Италия');
INSERT INTO countries (`id`, `value`) VALUES ('YE', 'Йемен');
INSERT INTO countries (`id`, `value`) VALUES ('CV', 'Кабо-Верде');
INSERT INTO countries (`id`, `value`) VALUES ('KZ', 'Казахстан');
INSERT INTO countries (`id`, `value`) VALUES ('KH', 'Камбоджа');
INSERT INTO countries (`id`, `value`) VALUES ('CM', 'Камерун');
INSERT INTO countries (`id`, `value`) VALUES ('CA', 'Канада');
INSERT INTO countries (`id`, `value`) VALUES ('QA', 'Катар');
INSERT INTO countries (`id`, `value`) VALUES ('KE', 'Кения');
INSERT INTO countries (`id`, `value`) VALUES ('CY', 'Кипр');
INSERT INTO countries (`id`, `value`) VALUES ('KG', 'Киргизия');
INSERT INTO countries (`id`, `value`) VALUES ('KI', 'Кирибати');
INSERT INTO countries (`id`, `value`) VALUES ('CN', 'Китай');
INSERT INTO countries (`id`, `value`) VALUES ('KP', 'КНДР');
INSERT INTO countries (`id`, `value`) VALUES ('CC', 'Кокосовые о-ва');
INSERT INTO countries (`id`, `value`) VALUES ('CO', 'Колумбия');
INSERT INTO countries (`id`, `value`) VALUES ('KM', 'Коморы');
INSERT INTO countries (`id`, `value`) VALUES ('CG', 'Конго - Браззавиль');
INSERT INTO countries (`id`, `value`) VALUES ('CD', 'Конго - Киншаса');
INSERT INTO countries (`id`, `value`) VALUES ('CR', 'Коста-Рика');
INSERT INTO countries (`id`, `value`) VALUES ('CI', 'Кот-д’Ивуар');
INSERT INTO countries (`id`, `value`) VALUES ('CU', 'Куба');
INSERT INTO countries (`id`, `value`) VALUES ('KW', 'Кувейт');
INSERT INTO countries (`id`, `value`) VALUES ('CW', 'Кюрасао');
INSERT INTO countries (`id`, `value`) VALUES ('LA', 'Лаос');
INSERT INTO countries (`id`, `value`) VALUES ('LV', 'Латвия');
INSERT INTO countries (`id`, `value`) VALUES ('LS', 'Лесото');
INSERT INTO countries (`id`, `value`) VALUES ('LR', 'Либерия');
INSERT INTO countries (`id`, `value`) VALUES ('LB', 'Ливан');
INSERT INTO countries (`id`, `value`) VALUES ('LY', 'Ливия');
INSERT INTO countries (`id`, `value`) VALUES ('LT', 'Литва');
INSERT INTO countries (`id`, `value`) VALUES ('LI', 'Лихтенштейн');
INSERT INTO countries (`id`, `value`) VALUES ('LU', 'Люксембург');
INSERT INTO countries (`id`, `value`) VALUES ('MU', 'Маврикий');
INSERT INTO countries (`id`, `value`) VALUES ('MR', 'Мавритания');
INSERT INTO countries (`id`, `value`) VALUES ('MG', 'Мадагаскар');
INSERT INTO countries (`id`, `value`) VALUES ('YT', 'Майотта');
INSERT INTO countries (`id`, `value`) VALUES ('MO', 'Макао (САР)');
INSERT INTO countries (`id`, `value`) VALUES ('MW', 'Малави');
INSERT INTO countries (`id`, `value`) VALUES ('MY', 'Малайзия');
INSERT INTO countries (`id`, `value`) VALUES ('ML', 'Мали');
INSERT INTO countries (`id`, `value`) VALUES ('MV', 'Мальдивы');
INSERT INTO countries (`id`, `value`) VALUES ('MT', 'Мальта');
INSERT INTO countries (`id`, `value`) VALUES ('MA', 'Марокко');
INSERT INTO countries (`id`, `value`) VALUES ('MQ', 'Мартиника');
INSERT INTO countries (`id`, `value`) VALUES ('MH', 'Маршалловы Острова');
INSERT INTO countries (`id`, `value`) VALUES ('MX', 'Мексика');
INSERT INTO countries (`id`, `value`) VALUES ('MZ', 'Мозамбик');
INSERT INTO countries (`id`, `value`) VALUES ('MD', 'Молдова');
INSERT INTO countries (`id`, `value`) VALUES ('MC', 'Монако');
INSERT INTO countries (`id`, `value`) VALUES ('MN', 'Монголия');
INSERT INTO countries (`id`, `value`) VALUES ('MS', 'Монтсеррат');
INSERT INTO countries (`id`, `value`) VALUES ('MM', 'Мьянма (Бирма)');
INSERT INTO countries (`id`, `value`) VALUES ('NA', 'Намибия');
INSERT INTO countries (`id`, `value`) VALUES ('NR', 'Науру');
INSERT INTO countries (`id`, `value`) VALUES ('NP', 'Непал');
INSERT INTO countries (`id`, `value`) VALUES ('NE', 'Нигер');
INSERT INTO countries (`id`, `value`) VALUES ('NG', 'Нигерия');
INSERT INTO countries (`id`, `value`) VALUES ('NL', 'Нидерланды');
INSERT INTO countries (`id`, `value`) VALUES ('NI', 'Никарагуа');
INSERT INTO countries (`id`, `value`) VALUES ('NU', 'Ниуэ');
INSERT INTO countries (`id`, `value`) VALUES ('NZ', 'Новая Зеландия');
INSERT INTO countries (`id`, `value`) VALUES ('NC', 'Новая Каледония');
INSERT INTO countries (`id`, `value`) VALUES ('NO', 'Норвегия');
INSERT INTO countries (`id`, `value`) VALUES ('BV', 'о-в Буве');
INSERT INTO countries (`id`, `value`) VALUES ('IM', 'о-в Мэн');
INSERT INTO countries (`id`, `value`) VALUES ('NF', 'о-в Норфолк');
INSERT INTO countries (`id`, `value`) VALUES ('CX', 'о-в Рождества');
INSERT INTO countries (`id`, `value`) VALUES ('SH', 'о-в Св. Елены');
INSERT INTO countries (`id`, `value`) VALUES ('PN', 'о-ва Питкэрн');
INSERT INTO countries (`id`, `value`) VALUES ('TC', 'о-ва Тёркс и Кайкос');
INSERT INTO countries (`id`, `value`) VALUES ('HM', 'о-ва Херд и Макдональд');
INSERT INTO countries (`id`, `value`) VALUES ('AE', 'ОАЭ');
INSERT INTO countries (`id`, `value`) VALUES ('OM', 'Оман');
INSERT INTO countries (`id`, `value`) VALUES ('KY', 'Острова Кайман');
INSERT INTO countries (`id`, `value`) VALUES ('CK', 'Острова Кука');
INSERT INTO countries (`id`, `value`) VALUES ('PK', 'Пакистан');
INSERT INTO countries (`id`, `value`) VALUES ('PW', 'Палау');
INSERT INTO countries (`id`, `value`) VALUES ('PS', 'Палестинские территории');
INSERT INTO countries (`id`, `value`) VALUES ('PA', 'Панама');
INSERT INTO countries (`id`, `value`) VALUES ('PG', 'Папуа — Новая Гвинея');
INSERT INTO countries (`id`, `value`) VALUES ('PY', 'Парагвай');
INSERT INTO countries (`id`, `value`) VALUES ('PE', 'Перу');
INSERT INTO countries (`id`, `value`) VALUES ('PL', 'Польша');
INSERT INTO countries (`id`, `value`) VALUES ('PT', 'Португалия');
INSERT INTO countries (`id`, `value`) VALUES ('PR', 'Пуэрто-Рико');
INSERT INTO countries (`id`, `value`) VALUES ('KR', 'Республика Корея');
INSERT INTO countries (`id`, `value`) VALUES ('RE', 'Реюньон');
INSERT INTO countries (`id`, `value`) VALUES ('RU', 'Россия');
INSERT INTO countries (`id`, `value`) VALUES ('RW', 'Руанда');
INSERT INTO countries (`id`, `value`) VALUES ('RO', 'Румыния');
INSERT INTO countries (`id`, `value`) VALUES ('SV', 'Сальвадор');
INSERT INTO countries (`id`, `value`) VALUES ('WS', 'Самоа');
INSERT INTO countries (`id`, `value`) VALUES ('SM', 'Сан-Марино');
INSERT INTO countries (`id`, `value`) VALUES ('ST', 'Сан-Томе и Принсипи');
INSERT INTO countries (`id`, `value`) VALUES ('SA', 'Саудовская Аравия');
INSERT INTO countries (`id`, `value`) VALUES ('MK', 'Северная Македония');
INSERT INTO countries (`id`, `value`) VALUES ('MP', 'Северные Марианские о-ва');
INSERT INTO countries (`id`, `value`) VALUES ('SC', 'Сейшельские Острова');
INSERT INTO countries (`id`, `value`) VALUES ('BL', 'Сен-Бартелеми');
INSERT INTO countries (`id`, `value`) VALUES ('MF', 'Сен-Мартен');
INSERT INTO countries (`id`, `value`) VALUES ('PM', 'Сен-Пьер и Микелон');
INSERT INTO countries (`id`, `value`) VALUES ('SN', 'Сенегал');
INSERT INTO countries (`id`, `value`) VALUES ('VC', 'Сент-Винсент и Гренадины');
INSERT INTO countries (`id`, `value`) VALUES ('KN', 'Сент-Китс и Невис');
INSERT INTO countries (`id`, `value`) VALUES ('LC', 'Сент-Люсия');
INSERT INTO countries (`id`, `value`) VALUES ('RS', 'Сербия');
INSERT INTO countries (`id`, `value`) VALUES ('SG', 'Сингапур');
INSERT INTO countries (`id`, `value`) VALUES ('SX', 'Синт-Мартен');
INSERT INTO countries (`id`, `value`) VALUES ('SY', 'Сирия');
INSERT INTO countries (`id`, `value`) VALUES ('SK', 'Словакия');
INSERT INTO countries (`id`, `value`) VALUES ('SI', 'Словения');
INSERT INTO countries (`id`, `value`) VALUES ('US', 'Соединенные Штаты');
INSERT INTO countries (`id`, `value`) VALUES ('SB', 'Соломоновы Острова');
INSERT INTO countries (`id`, `value`) VALUES ('SO', 'Сомали');
INSERT INTO countries (`id`, `value`) VALUES ('SD', 'Судан');
INSERT INTO countries (`id`, `value`) VALUES ('SR', 'Суринам');
INSERT INTO countries (`id`, `value`) VALUES ('SL', 'Сьерра-Леоне');
INSERT INTO countries (`id`, `value`) VALUES ('TJ', 'Таджикистан');
INSERT INTO countries (`id`, `value`) VALUES ('TH', 'Таиланд');
INSERT INTO countries (`id`, `value`) VALUES ('TW', 'Тайвань');
INSERT INTO countries (`id`, `value`) VALUES ('TZ', 'Танзания');
INSERT INTO countries (`id`, `value`) VALUES ('TG', 'Того');
INSERT INTO countries (`id`, `value`) VALUES ('TK', 'Токелау');
INSERT INTO countries (`id`, `value`) VALUES ('TO', 'Тонга');
INSERT INTO countries (`id`, `value`) VALUES ('TT', 'Тринидад и Тобаго');
INSERT INTO countries (`id`, `value`) VALUES ('TV', 'Тувалу');
INSERT INTO countries (`id`, `value`) VALUES ('TN', 'Тунис');
INSERT INTO countries (`id`, `value`) VALUES ('TM', 'Туркменистан');
INSERT INTO countries (`id`, `value`) VALUES ('TR', 'Турция');
INSERT INTO countries (`id`, `value`) VALUES ('UG', 'Уганда');
INSERT INTO countries (`id`, `value`) VALUES ('UZ', 'Узбекистан');
INSERT INTO countries (`id`, `value`) VALUES ('UA', 'Украина');
INSERT INTO countries (`id`, `value`) VALUES ('WF', 'Уоллис и Футуна');
INSERT INTO countries (`id`, `value`) VALUES ('UY', 'Уругвай');
INSERT INTO countries (`id`, `value`) VALUES ('FO', 'Фарерские о-ва');
INSERT INTO countries (`id`, `value`) VALUES ('FM', 'Федеративные Штаты Микронезии');
INSERT INTO countries (`id`, `value`) VALUES ('FJ', 'Фиджи');
INSERT INTO countries (`id`, `value`) VALUES ('PH', 'Филиппины');
INSERT INTO countries (`id`, `value`) VALUES ('FI', 'Финляндия');
INSERT INTO countries (`id`, `value`) VALUES ('FK', 'Фолклендские о-ва');
INSERT INTO countries (`id`, `value`) VALUES ('FR', 'Франция');
INSERT INTO countries (`id`, `value`) VALUES ('GF', 'Французская Гвиана');
INSERT INTO countries (`id`, `value`) VALUES ('PF', 'Французская Полинезия');
INSERT INTO countries (`id`, `value`) VALUES ('TF', 'Французские Южные территории');
INSERT INTO countries (`id`, `value`) VALUES ('HR', 'Хорватия');
INSERT INTO countries (`id`, `value`) VALUES ('CF', 'Центрально-Африканская Республика');
INSERT INTO countries (`id`, `value`) VALUES ('TD', 'Чад');
INSERT INTO countries (`id`, `value`) VALUES ('ME', 'Черногория');
INSERT INTO countries (`id`, `value`) VALUES ('CZ', 'Чехия');
INSERT INTO countries (`id`, `value`) VALUES ('CL', 'Чили');
INSERT INTO countries (`id`, `value`) VALUES ('CH', 'Швейцария');
INSERT INTO countries (`id`, `value`) VALUES ('SE', 'Швеция');
INSERT INTO countries (`id`, `value`) VALUES ('SJ', 'Шпицберген и Ян-Майен');
INSERT INTO countries (`id`, `value`) VALUES ('LK', 'Шри-Ланка');
INSERT INTO countries (`id`, `value`) VALUES ('EC', 'Эквадор');
INSERT INTO countries (`id`, `value`) VALUES ('GQ', 'Экваториальная Гвинея');
INSERT INTO countries (`id`, `value`) VALUES ('ER', 'Эритрея');
INSERT INTO countries (`id`, `value`) VALUES ('SZ', 'Эсватини');
INSERT INTO countries (`id`, `value`) VALUES ('EE', 'Эстония');
INSERT INTO countries (`id`, `value`) VALUES ('ET', 'Эфиопия');
INSERT INTO countries (`id`, `value`) VALUES ('GS', 'Южная Георгия и Южные Сандвичевы о-ва');
INSERT INTO countries (`id`, `value`) VALUES ('ZA', 'Южно-Африканская Республика');
INSERT INTO countries (`id`, `value`) VALUES ('SS', 'Южный Судан');
INSERT INTO countries (`id`, `value`) VALUES ('JM', 'Ямайка');
INSERT INTO countries (`id`, `value`) VALUES ('JP', 'Япония');
